/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class FrmSistema extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSistema.class.getName());

    /**
     * Creates new form FrmSistema
     */
    public FrmSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        cbxServicio = new javax.swing.JComboBox<>();
        btnAgendar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitas = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtHora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        cbxServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Limpieza Facial", "Masaje", "Botox" }));
        cbxServicio.setToolTipText("botox");
        cbxServicio.addActionListener(this::cbxServicioActionPerformed);

        btnAgendar.setText("Agendar Cita");
        btnAgendar.addActionListener(this::btnAgendarActionPerformed);

        tablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaCitas);

        jButton2.setText("Actualizar Cita");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Eliminar Cita");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel1.setText("Servicios");

        jLabel5.setText("Nombre");

        jLabel7.setText("Telefono");

        jLabel8.setText("Fecha");

        jLabel9.setText("Hora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHora, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(393, 393, 393))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgendar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgendar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void cbxServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxServicioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      // Dentro del evento del botón Eliminar:
int fila = tablaCitas.getSelectedRow(); 

    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(null, "Por favor, seleccione una cita de la tabla.");
    } else {
        int id = Integer.parseInt(tablaCitas.getValueAt(fila, 0).toString());

        int pregunta = javax.swing.JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar esta cita?");
        
        if (pregunta == 0) { 
            model.CitaDAO dao = new model.CitaDAO();
            if (dao.eliminarCita(id)) {
                javax.swing.JOptionPane.showMessageDialog(null, "Cita eliminada correctamente.");
                
                // Esto es para que la fila desaparezca de la vista de inmediato
                listarCitasEnTabla(); 
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Error al intentar eliminar de la base de datos.");
            }
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
       // Creamos los objetos necesarios
model.Cita cita = new model.Cita();
model.CitaDAO dao = new model.CitaDAO();

// 1. Validamos que los campos no estén vacíos
// 1. Validamos usando los cuadros de texto (txt)
if (!txtNombre.getText().equals("") && !txtTelefono.getText().equals("") && !txtFecha.getText().equals("")) {
    
    // 2. Pasamos la información de los cuadros de texto al objeto cita
    cita.setNombre(txtNombre.getText());
    cita.setTelefono(txtTelefono.getText());
    cita.setServicio(cbxServicio.getSelectedItem().toString());
    cita.setFecha(txtFecha.getText());
    cita.setHora(txtHora.getText());
    // 3. Intentamos registrar
    if (dao.registrarCita(cita)) {
        javax.swing.JOptionPane.showMessageDialog(null, "¡Cita agendada con éxito!");
        limpiarCampos();      // Función para vaciar los cuadritos
        listarCitasEnTabla(); // Refrescamos la tabla del administrador
    } else {
        javax.swing.JOptionPane.showMessageDialog(null, "Error: El horario ya está ocupado. Elige otro.");
    }

} else {
    javax.swing.JOptionPane.showMessageDialog(null, "Por favor, llena todos los campos.");
}
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int fila = tablaCitas.getSelectedRow();
    
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(null, "Por favor, seleccione una cita de la tabla para modificar.");
    } else {
        // 1. Capturamos los datos de los cuadros de texto
        model.Cita cita = new model.Cita();
        
        // Sacamos el ID de la fila seleccionada (columna 0)
        int id = Integer.parseInt(tablaCitas.getValueAt(fila, 0).toString());
        
        cita.setId(id);
        cita.setNombre(txtNombre.getText());
        cita.setTelefono(txtTelefono.getText());
        cita.setServicio(cbxServicio.getSelectedItem().toString());
        cita.setFecha(txtFecha.getText());
        cita.setHora(txtHora.getText());

        // 2. Llamamos al DAO para actualizar la base de datos
        model.CitaDAO dao = new model.CitaDAO();
        if (dao.modificarCita(cita)) {
            javax.swing.JOptionPane.showMessageDialog(null, "¡Cita actualizada correctamente!");
            listarCitasEnTabla(); // Para ver los cambios en la tabla
            limpiarCampos();      // Para vaciar los cuadritos después de actualizar
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Error al intentar actualizar los datos.");
        }
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmSistema().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JComboBox<String> cbxServicio;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCitas;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

public void listarCitasEnTabla() {
    model.CitaDAO dao = new model.CitaDAO();
    java.util.List<model.Cita> lista = dao.listarCitas();
    
    // 1. Definimos los títulos de las columnas de nuevo
    String[] titulos = {"ID", "Nombre", "Teléfono", "Servicio", "Fecha", "Hora"};
    javax.swing.table.DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel(null, titulos);
    
    // 2. Llenamos el modelo con los datos de la lista
    Object[] fila = new Object[6];
    for (int i = 0; i < lista.size(); i++) {
        fila[0] = lista.get(i).getId();
        fila[1] = lista.get(i).getNombre();
        fila[2] = lista.get(i).getTelefono();
        fila[3] = lista.get(i).getServicio();
        fila[4] = lista.get(i).getFecha();
        fila[5] = lista.get(i).getHora();
        modeloTabla.addRow(fila);
    }
    
    // 3. ¡ESTA ES LA LÍNEA MÁS IMPORTANTE! 
    // Le dice a la tabla visual que use este nuevo modelo con datos.
    tablaCitas.setModel(modeloTabla); 
}
public void limpiarCampos() {
    txtNombre.setText("");
    txtTelefono.setText("");
    txtFecha.setText("");
    txtHora.setText("");
}

}
